# ==============================================================================
# JKER OS - Pacman Configuration for ArchISO Build Engine
# ==============================================================================

[options]
HoldPkg      = pacman glibc
Architecture = auto

Color
CheckSpace
VerbosePkgLists
ParallelDownloads = 5

SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

# Standard Arch Repositories
[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

# Enable multilib for compatibility with 32-bit execution layers
[multilib]
Include = /etc/pacman.d/mirrorlist
