[Theme]
Name=jker-sddm
Description=JKER OS Tactical Minimalist SDDM Login Theme
Author=JKER OS Maintainers
Version=1.0
License=GPL
Type=sddm-theme

[General]
background=/usr/share/backgrounds/camo_red.jpg
font=Courier New
fontSize=12
color=#EDF2F4
accentColor=#D90429
boxColor=#1F2833
