# ==============================================================================
# JKER OS - Calamares GUI Installer Settings Configuration
# Defines sequence modules and visual layout of the GUI installer.
# ==============================================================================

modules-search: [ "/usr/lib/calamares/modules", "/usr/share/calamares/modules" ]

instances:
  - id:      jker-setup
    module:  shellprocess
    config:  shellprocess.conf

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - sources-yolodeploy
    - fstab
    - locale
    - keyboard
    - localecfg
    - users
    - networkcfg
    - hwclock
    - services-systemd
    - bootloader
    - shellprocess@jker-setup
    - umount
  - show:
    - finished

brand-image: "/usr/share/branding/jker_logo.png"
show-back-on-finished: false
EOF
